DistributedArchive.Web/Models/Tracker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Web;

namespace DistributedArchive.Web.Models
{
    public class Tracker
    {
        [Display(Name = "Tracker ID")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Tracker URL")]
        [Required]
        public string Url { get; set; }

        [Display(Name = "Tracker Name")]
        public string Name { get; set; }

        [Display(Name = "Tracker Info URL")]
        [RegexStringValidator("^https://")]
        public string InfoUrl { get; set; }
    }
}

DistributedArchive.Web/Models/TrackersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DistributedArchive.Web.Models
{
    public class TrackersViewModel
    {
        public Tracker EditedTracker { get; set; }
        public List<Tracker> ListOfTrackers { get; set; }
    }
}

DistributedArchive.Web/Controllers/TrackersController.cs
using AutoMapper;
using DistributedArchive.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistributedArchive.Web.Controllers
{
    public class TrackersController : Controller
    {
        Repository.Tracker.AbstractRepository repository;
        IMapper mapper;
        TrackersViewModel vm;

        public TrackersController()
        {
            mapper = MapperFactory.CreateMapper();

            repository = new Repository.Tracker.LocalDbRepository();

            vm = new TrackersViewModel();
            vm.EditedTracker = new Tracker();
            var trackers = repository.GetAll();
            vm.ListOfTrackers = mapper.Map<IEnumerable<Repository.Tracker>, List<Models.Tracker>>(trackers);
        }

        private Tracker GetTrackerModel(int id)
        {
            Repository.Tracker tracker = repository.GetOne(id);
            return mapper.Map<Repository.Tracker, Models.Tracker>(tracker);
        }

        // GET: Trackers
        public ActionResult Index()
        {
            ViewData["formAction"] = "AddNew";
            return View("TrackersIndex", vm);
        }

        // GET: Trackers/Details/5
        public ActionResult Details(int id)
        {
            return View("TrackerData", GetTrackerModel(id));
        }

        public ActionResult Remove(int id)
        {
            bool success = repository.Delete(repository.GetOne(id)) == Repository.ReturnCode.Success;
            TempData["formResult"] = success ? "Delete OK" : "Delete FAIL";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["formAction"] = "Edit";
            vm.EditedTracker = GetTrackerModel(id);
            return View("TrackersIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Tracker tracker, string formAction)
        {
            if(ModelState.IsValid && tracker != null)
            {
                TempData["formResult"] = "Edit OK";
                if(formAction == "AddNew")
                {
                    repository.Create(tracker.Url, tracker.Name, tracker.InfoUrl);
                }
                else
                {
                    var repoTracker = repository.GetOne(tracker.Id);
                    repoTracker.ProcessedUrl = tracker.Url;
                    repoTracker.Name = tracker.Name;
                    repoTracker.InfoLink = tracker.InfoUrl;
                    bool success = repository.Update(repoTracker) == Repository.ReturnCode.Success;
                    if(!success) TempData["formResult"] = "Edit FAIL";
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["formAction"] = "Edit";
                vm.EditedTracker = tracker;
                return View("TrackersIndex", vm);
            }
        }
    }
}

DistributedArchive.Web/Views/Trackers/TrackerData.cshtml
@model DistributedArchive.Web.Models.Tracker

@{
    ViewBag.Title = "TrackerData";
}

<h2>Datasheet of one tracker</h2>

@Html.ActionLink("Back to the list page", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Url)</td>
        <td>@Html.DisplayFor(m => m.Url)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.InfoUrl)</td>
        <td>@Html.DisplayFor(m => m.InfoUrl)</td>
    </tr>
</table>

DistributedArchive.Web/Views/Trackers/TrackerEdit.cshtml
@model DistributedArchive.Web.Models.Tracker

<h2>Edit tracker</h2>

@using (Html.BeginForm("Edit", "Trackers"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("formAction", ViewData["formAction"]?.ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Url)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Url)</div>

    <div class="editor-label">@Html.LabelFor(m => m.InfoUrl)</div>
    <div class="editor-field">@Html.EditorFor(m => m.InfoUrl)</div>

    <input type="submit" value="SEND" />
}

DistributedArchive.Web/Views/Trackers/TrackersIndex.cshtml
@model DistributedArchive.Web.Models.TrackersViewModel

@{
    ViewBag.Title = "TrackersIndex";
}

<h2>Known Trackers</h2>

<p style="color:red;font-weight:bold">@TempData["formResult"]</p>

@Html.Partial("TrackerEdit", Model.EditedTracker)

@Html.Partial("TrackersList", Model.ListOfTrackers)

DistributedArchive.Web/Views/Trackers/TrackersList.cshtml
@model IEnumerable<DistributedArchive.Web.Models.Tracker>

<h2>List of trackers</h2>

@if (Model.Count() == 0)
{
    <p>There are no trackers saved currently.</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Url)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var tracker in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => tracker.Name)</td>
                <td>@Html.DisplayFor(m => tracker.Url)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = tracker.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = tracker.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = tracker.Id })</td>
            </tr>
        }
    </table>
}